### ISSUE TITLE
Howto Link an External Library

### ISSUE THREAD

**Issue by mcxbain** [annexi-strayline/AURA#15]
With gprbuild i can link for example:
`package Linker is
      for Default_Switches ("ada") use ("-L/usr/lib/mysql", "-lmysqlclient", "-lz");
end Linker;`

Howto do that in AURA manifest ?

**Comment by Richard-Wai** [comment]
Sorry for the delay, I didn't see this until now!

Including external libraries (-lmysqlclient, for example) via the Build.External_Libraries package of the manifest to include external libraries. You can see an example in ASAP's INET subsystem [here](https://github.com/annexi-strayline/ASAP-INET/blob/main/inet-aura.ads).

As for linker options, Ada has defined the Linker_Options pragma for this purpose, and these are actually explicitly scanned by AURA. You could put this pragma in the manifest itself, and then make sure the resulting configuration package is withed by the program/package you are building.

AURA is designed as carefully as possible to not re-invent features already provided by the language, and this would be a good example of  that.

I will make an issue to add a note about this to the documentation.

Thanks for this question!
