### ISSUE TITLE
Use `aura/` directory for AURA files.

### ISSUE THREAD

**Issue by reznikmm** [annexi-strayline/AURA#4]
Hello,
Some people don't want to pollute project root directory with extra files. Could you modify AURA to search/use `aura/` directory if no AURA files found in the root? As a fallback mechanism.

What do you think?

**Comment by Richard-Wai** [comment]
This is a very interesting idea, probably even a great idea!

I might need to spend some time to think strategically about how to implement it, particularly when it comes to units that are auto-generated, but this idea has a lot of merit. 

Thanks for that!

**Comment by thindil** [comment]
I also agree that this is an awesome idea, but maybe call the directory `.aura` (with leading dot) not `aura`? I think it better suit a standard way to handle things in a project, like `.git`, `.vscode` etc.

**Comment by Richard-Wai** [comment]
In fact AURA does create .aura directory to hold state information between runs, as well as to cache git repositories.

The idea of the aura subsystem itself is that it can be part of the actual codebase. This is a key component of the autoconfiguration process. So for that reason, we wouldn't want to put them in a hidden place. The aura subsystem is fully accessible from the project codebase itself, as well as any installed AURA subsystems.

**Comment by thindil** [comment]
I understand. Ok, then please ignore my proposition and just keep the vote up for the main proposition. 😄

**Comment by Richard-Wai** [comment]
Change applies as of v0.2 via a new depreciation mechanism.
